<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="COS10026 Week 08 Lab - PHP sessions, include files and hidden fields">
	<meta name="author" content="Zadeed Haque">
	<title><?php echo $pageTitle; ?></title>
</head>
<body>
	<header>
		<h1>COS10026 Lab 08 &ndash; PHP Login</h1>
	</header>
	<main>
